<div class="panel-body">
    {{#if visible}}
        <p class="text-muted small">{{translate 'formatoActaVisitaHelp' category='ActaVisita'}}</p>
        {{#if hasAutoPdf}}
            <p class="text-success small">
                <span class="fas fa-check-circle"></span>
                {{translate 'formatoActaVisitaAutoGenerated' category='ActaVisita'}}
            </p>
            <a class="btn btn-default btn-block" href="{{autoPdfUrl}}" target="_blank" rel="noopener">
                <span class="fas fa-file-pdf"></span> {{autoPdfName}}
            </a>
        {{/if}}
        <button type="button" class="btn btn-default btn-block" data-action="downloadFormatoActa" data-format="docx">
            <span class="fas fa-file-word"></span> {{translate 'downloadFormatoActaWord' category='ActaVisita'}}
        </button>
        <button type="button" class="btn btn-default btn-block" data-action="downloadFormatoActa" data-format="pdf">
            <span class="fas fa-file-pdf"></span> {{translate 'downloadFormatoActaPdf' category='ActaVisita'}}
        </button>
    {{else}}
        <p class="text-muted small">{{translate 'formatoActaVisitaUnavailable' category='ActaVisita'}}</p>
    {{/if}}
</div>
